### ISSUE TITLE
Why alpha and mu are global, not parameter-wise?

### ISSUE THREAD

**Issue by glogowski-wojciech** [JianGoForIt/YellowFin_Pytorch#13]
Hi! Thank you for your great work!

Could you tell why you decided to use one global _alpha_ and one global _mu_ for whole the model instead of creating a separate _alpha_ and _mu_ for each matrix of weights in the model? The other approach seems to be more natural to me because each matrix of weights might have different distributions of its values and values of its gradient. Did you consider it? Do you see a reason not to do so?

**Comment by JianGoForIt** [comment]
Hi @glogowski-wojciech,

We have not extensively trying out per-layer lr/momentum. In YF, we want to demonstrate momentum is related the range of curvatures of all variables. That is the reason why we decide to use single lr/momentum. I am not sure in a general setting what would happen if there is multiple momentum. If the Hessian can be closely approximated by a diagonal block matrix, multiple momentum might also work I think. On the other hand, it might also be possible the Hessian can not be properly approximated by diagonal block matrix, then it might violate our analysis on analyzing the range of curvature. We do not have direct empirical evidence on this question :).
