### ISSUE TITLE
Python3 changes for word_language_model

### ISSUE THREAD

**Issue by esvhd** [JianGoForIt/YellowFin_Pytorch#2]
Hi there,

Thanks for sharing this amazing piece of work.

I made some small changes to the `word_language_model`'s `main.py` script to make it work with `python3`. The changes were essentially related to `print` function calls and a couple of minor indentations.

Tested and the script now runs successfully with `Python 3.6`. Would you be interested in merging it? 

Thanks.

**Comment by JianGoForIt** [comment]
Hi @esvhd, Thanks for the pull request. We have merged it.
