### ISSUE TITLE
AttributeError: 'YFOptimizer' object has no attribute '_state_checkpoint'

### ISSUE THREAD

**Issue by bapi** [JianGoForIt/YellowFin_Pytorch#24]
Hi,

The following error pops up when I use yellowfin.py in my setup.
```
File "/home/bchatter/Documents/workspace/python/async-opt/resnet_cifar_yellowfin/yellowfin.py", line 568, in step
    self.load_state_dict_perturb(copy.deepcopy(self._state_checkpoint) )
AttributeError: 'YFOptimizer' object has no attribute '_state_checkpoint'
```

I attempted solving this issue by copying the line 543 in yellowfin.py `self._state_checkpoint = copy.deepcopy(self.state_dict() )` just above the line 568. However, with that the optimizer starts to be non-converging (at times diverges, but certainly does not converge).

Could you please look at the issue?

**Comment by JianGoForIt** [comment]
Hi Bapi,

I think line 568 comes into play when numerical stability issues comes out. The purpose of this line is to reload and slightly perturb the last saved stable check point. If you directly copy line 543 here, it is actually still loading the current problematic model with numerical issues, that can be the reason that it does not converge.

I would suggest looking into the reason why "AttributeError: 'YFOptimizer' object has no attribute '_state_checkpoint'" emerge, you may check the code from line 536 to 543 to see why checkpoint is not saved.

Cheers,

**Comment by JianGoForIt** [comment]
Btw, @bapi I think the error is probably triggered by the discrepancy between old and new pytorch version. Basically, the possible reason why line 568 is executed can be the improper access to 0-d tensors for > pytorch 0.4 (e.g. tensor.data[0] is OK for 0-d tensor in <= pytorch 0.3). My latest commit resolved this, you may want to try out.

**Comment by bapi** [comment]
Hi Jian,

It works properly now. Thanks for the response.
